apiVersion: apps/v1
kind: Deployment
metadata:
  name: updateworker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label-updateworker
  template:
    metadata:
      labels:
        app: label-updateworker
    spec:
      containers:
        - name: cont-updateworker
          image: updateworkerv1:latest
          imagePullPolicy: Never
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq.default.svc.cluster.local
            - name: ASPNETCORE_URLS
              value: http://*:8087
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: guest
            - name: RABBITMQ_PASS
              value: guest
            - name: DB_CONNECTIONSTRING
              value: Server=mssql-nodeport.default.svc.cluster.local,1433;Database=ContactDB;User Id=sa;Password=@Senha123;Encrypt=False;
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8087
