apiVersion: apps/v1
kind: Deployment
metadata:
  name: createapi
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
      labels:
        app: label-createapi
    spec:
      containers:
      - name: cont-createapi
        image: contactcreateapiv1:latest
        imagePullPolicy: Never
        env: 
          #- name: RABBITMQ_HOST
          #  value: host.docker.internal
          - name: ASPNETCORE_URLS
            value: http://*:8080         
          - name: RABBITMQ_PORT
            value: "5672"
          - name: RABBITMQ_USER
            value: guest
          - name: RABBITMQ_PASS
            value: guest         
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
  selector:
    matchLabels:
      app: label-createapi
