apiVersion: apps/v1
kind: Deployment
metadata:
  name: createworker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label-createworker
  template:
    metadata:
      labels:
        app: label-createworker
    spec:
      containers:
      - name: cont-createworker
        image: createworkerv1:latest
        imagePullPolicy: Never
        env:          
          - name: RABBITMQ_HOST
            value: host.docker.internal
          - name: ASPNETCORE_URLS
            value: http://*:8085
          - name: RABBITMQ_PORT
            value: "5672"
          - name: RABBITMQ_USER
            value: guest
          - name: RABBITMQ_PASS
            value: guest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8085
