apiVersion: apps/v1
kind: Deployment
metadata:
  name: deleteapi
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8082"
      labels:
        app: label-deleteapi
    spec:
      containers:
        - name: cont-deleteapi
          image: contactdeleteapiv1:latest
          imagePullPolicy: Never
          envFrom:
              - secretRef:
                  name: database-secrets
              - secretRef:
                  name: rabbitmq-secrets
              - configMapRef:
                  name: config-rabbitmq
              - configMapRef:
                  name: config-database
          env:
              - name: ASPNETCORE_URLS
                value: http://*:8082
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8082
  selector:
    matchLabels:
      app: label-deleteapi
