apiVersion: apps/v1
kind: Deployment
metadata:
  name: deleteworker
  annotations:
    description: "Deployment para o WORKER de Delecao"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label-deleteworker
  template:
    metadata:
      labels:
        app: label-deleteworker
    spec:
      containers:
      - name: cont-deleteworker
        image: deleteworkerv1:latest
        imagePullPolicy: Never
        envFrom:
            - secretRef:
                name: database-secrets
            - secretRef:
                name: rabbitmq-secrets
            - configMapRef:
                name: config-rabbitmq
            - configMapRef:
                name: config-database
        env:
            - name: ASPNETCORE_URLS
              value: http://*:8086
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8086
