apiVersion: apps/v1
kind: Deployment
metadata:
  name: createapi
  annotations:
    description: "Deployment para a API de Criação"
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
      labels:
        app: label-createapi
    spec:
      containers:
      - name: cont-createapi
        image: contactcreateapiv1:latest
        imagePullPolicy: Never
        envFrom:
            - secretRef:
                name: database-secrets
            - secretRef:
                name: rabbitmq-secrets
            - configMapRef:
                name: config-rabbitmq
            - configMapRef:
                name: config-database
        env:
            - name: ASPNETCORE_URLS
              value: http://*:8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
  selector:
    matchLabels:
      app: label-createapi
