apiVersion: apps/v1
kind: Deployment
metadata:
  name: createworker
  annotations:
    description: "Deployment para o WORKER de Criacao"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label-createworker
  template:
    metadata:
      labels:
        app: label-createworker
    spec:
      containers:
      - name: cont-createworker
        image: createworkerv1:latest
        imagePullPolicy: Never
        envFrom:
            - secretRef:
                name: database-secrets
            - secretRef:
                name: rabbitmq-secrets
            - configMapRef:
                name: config-rabbitmq
            - configMapRef:
                name: config-database
        env:
            - name: ASPNETCORE_URLS
              value: http://*:8085
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8085
