apiVersion: apps/v1
kind: Deployment
metadata:
  name: readapi
  annotations:
    description: "Deployment para a API de Consulta"
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8083"
      labels:
        app: label-readapi
    spec:
      containers:
      - name: cont-readapi
        image: contactreadapiv1:latest
        imagePullPolicy: Never
        envFrom:
            - secretRef:
                name: database-secrets
            - configMapRef:
                name: config-database
        env:
            - name: ASPNETCORE_URLS
              value: http://*:8083
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8083
  selector:
    matchLabels:
      app: label-readapi
