apiVersion: v1
kind: Service
metadata:
  name: svc-readapi
  annotations:
    description: "Servico para expor o WORKER de Criacao dentro do cluster para os demais pods"
spec:
  type: NodePort
  selector:
    app: label-readapi
  ports:
  - port: 8083
    nodePort: 30002
    
