apiVersion: v1
kind: Service
metadata:
  name: svc-deleteapi
  annotations:
    description: "Servico para expor a API de criacao para fora do cluster"
spec:
  type: NodePort
  selector:
    app: label-deleteapi
  ports:
  - port: 8082
    nodePort: 30005
    
