apiVersion: v1
kind: Service
metadata:
  name: svc-createapi
  annotations:
    description: "Servico para expor a API de Criacao para fora do cluster"
spec:
  type: NodePort
  selector:
    app: label-createapi
  ports:
  - port: 8080
    nodePort: 30000
    
