apiVersion: v1
kind: Service
metadata:
  name: svc-createworker
  annotations:
    description: "Servico para expor o WORKER de criacao dentro do cluster para os demais pods"
spec:
  type: NodePort
  selector:
    app: label-createworker
  ports:
  - port: 8085
    nodePort: 30001
    
    
