apiVersion: v1
kind: Service
metadata:
  name: svc-updateapi
  annotations:
    description: "Servico para expor a API de criacao para fora do cluster"
spec:
  type: NodePort
  selector:
    app: label-updateapi
  ports:
  - port: 8084
    nodePort: 30003
