apiVersion: v1
kind: Service
metadata:
  name: mssql-nodeport
spec:
  type: NodePort
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 30033
